<a href="https://colab.research.google.com/github/prashantnarwade807-star/PDS-ASSINGMENT/blob/main/Practicle_3_Prashant_Govind_Narwade_%2CB_15%2CB1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NAME: Prashant Govind Narwade Roll no: B-15 class : SY-B ,AIDSBach : B 1

 Aim : Data Wrangling with pandas: Manipulate and transform data to suit the analysis

1.  **What is data wrangling? Explain the difference between data wrangling and data preprocessing.**

    *   **Data Wrangling (also known as Data Munging):** This is the process of transforming and mapping data from one "raw" data form into another format with the intent of making it more appropriate and valuable for a variety of downstream purposes such as analytics.
        It involves several steps like data collection, data cleaning, structuring, enriching, validating, and publishing.

    *   **Data Preprocessing:** This is a subset of data wrangling focused on preparing raw data for machine learning models. It primarily deals with cleaning and transforming data to a format that can be easily fed into an algorithm. Key tasks include handling missing values, encoding categorical data, feature scaling, and data splitting.

    *   **Difference:** Data wrangling is a broader concept that encompasses all activities from gathering raw data to making it usable for any analytical task, including cleaning, transforming, and validating. Data preprocessing is specifically about preparing data for machine learning algorithms, which is a part of the larger data wrangling process.

2.  **What is the importance of exploratory data analysis (EDA) in Pandas?**

    Exploratory Data Analysis (EDA) in Pandas is crucial for several reasons:

    *   **Understanding Data:** It helps in gaining insights into the dataset's main characteristics, underlying structure, outliers, and anomalies.
    *   **Identifying Patterns:** It allows for the discovery of patterns, relationships, and trends between variables.
    *   **Formulating Hypotheses:** It assists in developing hypotheses for further investigation or model building.
    *   **Detecting Errors:** It can reveal data quality issues, missing values, or inconsistent data entries.
    *   **Feature Engineering:** Insights gained from EDA can guide the creation of new features that might improve model performance.
    *   **Selecting Appropriate Models:** Understanding data distributions and relationships can help in choosing the most suitable statistical or machine learning models.
    *   **Data Cleaning:** It informs the necessary data cleaning and transformation steps before formal analysis or modeling.

3.  **What are the main differences between Series, DataFrame, and Panel?**

    *   **Series:** A one-dimensional labeled array capable of holding any data type (integers, strings, floats, Python objects, etc.). It's like a single column in a spreadsheet or a SQL table. It has an associated data label (index).

    *   **DataFrame:** A two-dimensional labeled data structure with columns of potentially different types. It's the most commonly used Pandas object and can be thought of as a spreadsheet or a SQL table, or a dictionary of Series objects. It has both a row index and a column index.

    *   **Panel:** A three-dimensional labeled data structure. It can be thought of as a dictionary of DataFrames. While it was part of earlier Pandas versions, the `Panel` object has been deprecated since Pandas 0.25.0 in favor of MultiIndex DataFrames or xarray for handling 3D+ data.

4.  **Explain the use of:**
    a.  `isnull()`
    b.  `notnull()`
    c.  `dropna()`
    d.  `fillna()`

    These are all essential functions in Pandas for handling missing data:

    *   **`isnull()`:** Returns a boolean Series or DataFrame indicating where the values are `NaN` (Not a Number) or `None`. It's used to detect missing values. `True` indicates a missing value, `False` indicates a non-missing value.
        *   *Example:* `df.isnull()`

    *   **`notnull()`:** This is the inverse of `isnull()`. It returns a boolean Series or DataFrame indicating where the values are *not* `NaN` or `None`. `True` indicates a non-missing value, `False` indicates a missing value.
        *   *Example:* `df.notnull()`

    *   **`dropna()`:** Used to remove missing values. It can drop rows or columns that contain `NaN` or `None` values.
        *   *Parameters:* `axis` (0 for rows, 1 for columns), `how` ('any' to drop if *any* NA is present, 'all' to drop if *all* values are NA), `inplace` (to modify the DataFrame directly).
        *   *Example:* `df.dropna()` (drops rows with any missing value), `df.dropna(axis=1)` (drops columns with any missing value).

    *   **`fillna()`:** Used to fill missing `NaN` or `None` values with a specified value or method.
        *   *Parameters:* Can take a scalar value, a dictionary (for different values per column), a method like `'ffill'` (forward fill) or `'bfill'` (backward fill), and `inplace`.
        *   *Example:* `df.fillna(0)` (fills all NaN with 0), `df.fillna(df.mean())` (fills NaN with column means), `df.fillna(method='ffill')`.

5.  **What is column transformation and why is it important in data analysis?**

    **Column Transformation** refers to the process of applying a mathematical function or an operation to a column (or multiple columns) in a dataset to create new features, change the scale of existing features, or convert them into a more suitable format for analysis or modeling.

    **Why it's important:**

    *   **Improved Model Performance:** Many machine learning algorithms perform better when input features have certain distributions (e.g., normal distribution) or scales. Transformations can help meet these requirements.
    *   **Handling Skewness:** Highly skewed data can negatively impact model performance. Transformations like log, square root, or reciprocal can reduce skewness.
    *   **Standardization/Normalization:** Bringing features to a similar scale prevents features with larger values from dominating the learning process (e.g., `StandardScaler`, `MinMaxScaler`).
    *   **Feature Engineering:** Creating new features from existing ones (e.g., extracting month/year from a date column, creating interaction terms) can provide more predictive power.
    *   **Categorical Encoding:** Converting categorical variables into numerical representations (e.g., One-Hot Encoding, Label Encoding) is essential as most algorithms only work with numerical data.
    *   **Addressing Outliers:** Certain transformations can reduce the impact of extreme outliers.
    *   **Meeting Algorithm Assumptions:** Some statistical tests or algorithms assume linearity, normality, or homoscedasticity, which transformations can help achieve.

In [ ]:
import pandas as pd
import numpy as np

# 1. Create a sample DataFrame with missing values
data = {
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam', 'Speaker', 'Headset', 'Microphone'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Peripherals', 'Audio', 'Audio', 'Audio'],
    'Price': [1200, 25, np.nan, 300, 50, np.nan, 150, 80],
    'Quantity': [10, 50, 20, 5, 30, 15, np.nan, 25],
    'Rating': [4.5, 4.0, 3.8, 4.7, np.nan, 4.2, 4.1, 3.9]
}
df = pd.DataFrame(data)
print("Original DataFrame with NaNs:")
display(df)

# 2. Handle missing values using fillna()
# Fill missing 'Price' with the mean price
df['Price'] = df['Price'].fillna(df['Price'].mean())
# Fill missing 'Quantity' with 0
df['Quantity'] = df['Quantity'].fillna(0)
# Fill missing 'Rating' with the median rating
df['Rating'] = df['Rating'].fillna(df['Rating'].median())
print("\nDataFrame after filling missing values:")
display(df)

# Verify no more missing values
print("\nMissing values after fillna():")
display(df.isnull().sum())

# 3. Perform a column transformation: Calculate 'TotalSales'
# Convert 'Category' to categorical type for efficiency
df['Category'] = df['Category'].astype('category')
# Calculate 'TotalSales'
df['TotalSales'] = df['Price'] * df['Quantity']

print("\nDataFrame after column transformation (TotalSales and Category type change):")
display(df)
print("\nDataFrame Info after transformations:")
df.info()

Original DataFrame with NaNs:

      Product     Category   Price  Quantity  Rating
0      Laptop  Electronics  1200.0      10.0     4.5
1       Mouse  Electronics    25.0      50.0     4.0
2    Keyboard  Electronics     NaN      20.0     3.8
3     Monitor  Electronics   300.0       5.0     4.7
4      Webcam  Peripherals    50.0      30.0     NaN
5     Speaker        Audio     NaN      15.0     4.2
6     Headset        Audio   150.0       NaN     4.1
7  Microphone        Audio    80.0      25.0     3.9

DataFrame after filling missing values:

      Product     Category        Price  Quantity  Rating
0      Laptop  Electronics  1200.000000      10.0     4.5
1       Mouse  Electronics    25.000000      50.0     4.0
2    Keyboard  Electronics   300.833333      20.0     3.8
3     Monitor  Electronics   300.000000       5.0     4.7
4      Webcam  Peripherals    50.000000      30.0     4.1
5     Speaker        Audio   300.833333      15.0     4.2
6     Headset        Audio   150.000000       0.0     4.1
7  Microphone        Audio    80.000000      25.0     3.9

Missing values after fillna():

Product     0
Category    0
Price       0
Quantity    0
Rating      0
dtype: int64

DataFrame after column transformation (TotalSales and Category type change):

      Product     Category        Price  Quantity  Rating    TotalSales
0      Laptop  Electronics  1200.000000      10.0     4.5  12000.000000
1       Mouse  Electronics    25.000000      50.0     4.0   1250.000000
2    Keyboard  Electronics   300.833333      20.0     3.8   6016.666667
3     Monitor  Electronics   300.000000       5.0     4.7   1500.000000
4      Webcam  Peripherals    50.000000      30.0     4.1   1500.000000
5     Speaker        Audio   300.833333      15.0     4.2   4512.500000
6     Headset        Audio   150.000000       0.0     4.1      0.000000
7  Microphone        Audio    80.000000      25.0     3.9   2000.000000

DataFrame Info after transformations:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Product     8 non-null      object
 1   Category    8 non-null      category
 2   Price       8 non-null      float64
 3   Quantity    8 non-null      float64
 4   Rating      8 non-null      float64
 5   TotalSales  8 non-null      float64
dtypes: category(1), float64(4), object(1)
memory usage: 592.0+ bytes

## Conclusion: Data Wrangling with Pandas

In this section, we've explored the fundamental aspects of data wrangling using the Pandas library in Python. We covered:

*   **Understanding Missing Data:** We learned how to identify missing values using `isnull()` and `notnull()`.
*   **Handling Missing Data:** We demonstrated effective strategies for dealing with `NaN` values, including dropping rows/columns with `dropna()` and intelligently filling them using `fillna()` with methods like mean, median, or a constant value.
*   **Column Transformation:** We saw how to create new, more informative features (like `TotalSales`) from existing ones and how to optimize data types (e.g., converting 'Category' to `category`) for better performance and memory management.

These techniques are crucial for cleaning, preparing, and transforming raw data into a format suitable for in-depth analysis and machine learning models, ensuring the reliability and accuracy of subsequent insights.